# Generated by Django 4.0.2 on 2022-02-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
