# Generated by Django 4.0.2 on 2022-03-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerapp', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='myimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imagegallery/')),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
