# Generated by Django 4.0.4 on 2022-04-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scannerapp', '0003_myimages_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='mypdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
